# -*- coding:utf-8 -*-

questions = [
    # Asia
    {"name": "China", "state": "Asia", "demonym": "Chinese", "language": "Chinese", "currency": "Renminbi", "capital": "Beijing"},
    {"name": "India", "state": "Asia", "demonym": "Indian", "language": "Hindi", "currency": "rupee", "capital": "New Delhi"},
    {"name": "Indonesia", "state": "Asia", "demonym": "Indonesian", "language": "Indonesian", "currency": "rupiah", "capital": "Jakarta"},
    {"name": "Pakistan", "state": "Asia", "demonym": "Pakistani", "language": "Urdu", "currency": "rupee", "capital": "Islamabad"},
    {"name": "Bangladesh", "state": "Asia", "demonym": "Bangladeshi", "language": "Bengali", "currency": "Taka", "capital": "Dhaka"},
    {"name": "Philippines", "state": "Asia", "demonym": "Philippine", "language": "Filipino", "currency": "Peso", "capital": "Manila"},
    {"name": "Japan", "state": "Asia", "demonym": "Japanese", "language": "Japanese", "currency": "Yen", "capital": "Tokyo"},
    {"name": "Iran", "state": "Asia", "demonym": "Iranian", "language": "Persian", "currency": "Rial", "capital": "Tehran"},
    {"name": "Thailand", "state": "Asia", "demonym": "Thai", "language": "Thai", "currency": "Baht", "capital": "Bangkok"},
    {"name": "Myanmar", "state": "Asia", "demonym": "Myanma", "language": "Burmese", "currency": "Kyat", "capital": "Naypyidaw"},
    {"name": "South Korea", "state": "Asia", "demonym": "", "language": "Korean", "currency": "South Korean won", "capital": "Seoul"},
    {"name": "Iraq", "state": "Asia", "demonym": "Iraqi", "language": "Arabic", "currency": "Iraqi dinar", "capital": "Baghdad"},
    {"name": "Afghanistan", "state": "Asia", "demonym": "Afghan", "language": "Pashto", "currency": "Afghani", "capital": "Kabul"},
    {"name": "Saudi Arabia", "state": "Asia", "demonym": "Saudi", "language": "Arabic", "currency": "Saudi riyal", "capital": "Riyadh"},
    {"name": "United Arab Emirates", "state": "Asia", "demonym": "Emiratis", "language": "Arabic", "currency": "UAE dirham", "capital": "Abu Dhabi"},
    {"name": "Tajikistan", "state": "Asia", "demonym": "Tajik", "language": "Tajik", "currency": "Somoni", "capital": "Dushanbe"},
    {"name": "Laos", "state": "Asia", "demonym": "Laotian", "language": "Lao", "currency": "Kip", "capital": "Vientiane"},
    {"name": "Jordan", "state": "Asia", "demonym": "Jordanian", "language": "Arabic", "currency": "Dinar", "capital": "Amman"},
    {"name": "Qatar", "state": "Asia", "demonym": "Qatari", "language": "Arabic", "currency": "Riyal", "capital": "Doha"},
    {"name": "Bahrain", "state": "Asia", "demonym": "Bahraini", "language": "Arabic", "currency": "Bahraini dinar", "capital": "Manama"},
    {"name": "Timor-Leste", "state": "Asia", "demonym": "East Timorese", "language": "Tetum", "currency": "United States Dollar", "capital": "Dili"},
    {"name": "Bhutan", "state": "Asia", "demonym": "Bhutanese", "language": "Dzongkha", "currency": "Ngultrum", "capital": "Thimphu"},
    {"name": "Brunei", "state": "Asia", "demonym": "Bruneian", "language": "Malay", "currency": "Brunei dollar", "capital": "Bandar Seri Begawan"},
    {"name": "Maldives", "state": "Asia", "demonym": "Maldivian", "language": "Maldivian", "currency": "Maldivian rufiyaa", "capital": "Malé"},
    {"name": "Belize", "state": "Asia", "demonym": "Belizean", "language": "English", "currency": "Belize dollar", "capital": "Belmopan"},
    {"name": "Kyrgyzstan", "state": "Asia", "demonym": "Kyrgyz", "language": "Kyrgyz", "currency": "Som", "capital": "Bishkek"},
    {"name": "Lebanon", "state": "Asia", "demonym": "Lebanese", "language": "Arabic", "currency": "Lebanese pound", "capital": "Beirut"},
    {"name": "Singapore", "state": "Asia", "demonym": "Singaporean", "language": "English", "currency": "Singapore dollar", "capital": "Singapore"},
    {"name": "Oman", "state": "Asia", "demonym": "Omani", "language": "Arabic", "currency": "Rial", "capital": "Muscat"},
    {"name": "Kuwait", "state": "Asia", "demonym": "Kuwaiti", "language": "Arabic", "currency": "Kuwaiti dinar", "capital": "Kuwait City"},
    {"name": "State of Palestine", "state": "Asia", "demonym": "Palestinian", "language": "Arabic", "currency": "Egyptian pound", "capital": "Jerusalem"},
    {"name": "Turkmenistan", "state": "Asia", "demonym": "Turkmen", "language": "Turkmen", "currency": "Turkmen new manat", "capital": "Ashgabat"},
    {"name": "Malaysia", "state": "Asia", "demonym": "Malaysian", "language": "Bahasa Malaysia", "currency": "Ringgit", "capital": "Kuala Lumpur"},
    {"name": "Uzbekistan", "state": "Asia", "demonym": "Uzbek", "language": "Uzbek", "currency": "Uzbekistan som", "capital": "Tashkent"},
    {"name": "Sri Lanka", "state": "Asia", "demonym": "Sri Lankan", "language": "Sinhalese", "currency": "Sri Lankan rupee", "capital": "Sri Jayawardenepura Kotte"},
    {"name": "Nepal", "state": "Asia", "demonym": "Nepali", "language": "Nepali", "currency": "Nepalese rupee", "capital": "and largest city"},
    {"name": "North Korea", "state": "Asia", "demonym": "North Korean", "language": "Korean", "currency": "North Korean won", "capital": "Pyongyang"},
    {"name": "Syria", "state": "Asia", "demonym": "Syrian", "language": "Arabic", "currency": "Syrian pound", "capital": "Damascus"},
    {"name": "Yemen", "state": "Asia", "demonym": "Yemeni, Yemenite", "language": "Arabic", "currency": "Yemeni rial", "capital": "Sana'a"},
    {"name": "Cambodia", "state": "Asia", "demonym": "Cambodian, Kampuchean", "language": "Khmer", "currency": "Riel", "capital": "Phnom Penh"},
    # Europe
    {"name": "Russia", "state": "Europe", "demonym": "Russian", "language": "Russian", "currency": "ruble", "capital": "Moscow"},
    {"name": "Germany", "state": "Europe", "demonym": "German", "language": "German", "currency": "Euro", "capital": "Berlin"},
    {"name": "Turkey", "state": "Europe", "demonym": "Turkish", "language": "Turkish", "currency": "lira", "capital": "Ankara"},
    {"name": "U.K.", "state": "Europe", "demonym": "British", "language": "English", "currency": "Pound", "capital": "London"},
    {"name": "France", "state": "Europe", "demonym": "French", "language": "French", "currency": "Euro", "capital": "Paris"},
    {"name": "Italy", "state": "Europe", "demonym": "Italian", "language": "Italian", "currency": "Euro", "capital": "Rome"},
    {"name": "Spain", "state": "Europe", "demonym": "Spanish", "language": "Spanish", "currency": "Euro", "capital": "Madrid"},
    {"name": "Ukraine", "state": "Europe", "demonym": "Ukrainian", "language": "Ukrainian", "currency": "Ukrainian hryvnia", "capital": "Kiev"},
    # North America
    {"name": "U.S.", "state": "North America", "demonym": "American", "language": "English", "currency": "dollar", "capital": "Washington, D.C."},
    {"name": "Mexico", "state": "North America", "demonym": "Mexican", "language": "Spanish", "currency": "Peso", "capital": "Mexico City"},
    {"name": "Canada", "state": "North America", "demonym": "Canadian", "language": "English", "currency": "Canadian dollar", "capital": "Ottawa"},
    # South America
    {"name": "Colombia", "state": "South America", "demonym": "Colombian", "language": "Spanish", "currency": "Peso", "capital": "Bogotá"},
    {"name": "Argentina", "state": "South America", "demonym": "Argentine", "language": "Spanish", "currency": "Peso", "capital": "Buenos Aires"},
    # Africa
    {"name": "Nigeria", "state": "Africa", "demonym": "Nigerian", "language": "English", "currency": "Naira", "capital": "Abuja"},
    {"name": "Ethiopia", "state": "Africa", "demonym": "Ethiopian", "language": "Ethiopian", "currency": "Birr", "capital": "Addis Ababa"},
    {"name": "Egypt", "state": "Africa", "demonym": "Egyptian", "language": "Arabic", "currency": "Egyptian pound", "capital": "Cairo"},
    {"name": "DR Congo", "state": "Africa", "demonym": "Congolese", "language": "French", "currency": "franc", "capital": "Kinshasa"},
    {"name": "Tanzania", "state": "Africa", "demonym": "Tanzanian", "language": "	Swahili", "currency": "Tanzanian shilling", "capital": "Dodoma"},
    {"name": "South Africa", "state": "Africa", "demonym": "South African", "language": "IsiZulu", "currency": "rand", "capital": "Pretoria"},
    {"name": "Kenya", "state": "Africa", "demonym": "Kenyan", "language": "Kiswahili", "currency": "Kenyan shilling", "capital": "Nairobi"},
    {"name": "Sudan", "state": "Africa", "demonym": "Sudanese", "language": "Arabic", "currency": "Sudanese pound", "capital": "Khartoum"},
    {"name": "Uganda", "state": "Africa", "demonym": "Ugandan", "language": "English", "currency": "Ugandan shilling", "capital": "Kampala"},
    {"name": "Algeria", "state": "Africa", "demonym": "Algerian", "language": "Arabic", "currency": "Dinar", "capital": "Algiers"},
    {"name": "Morocco", "state": "Africa", "demonym": "Moroccan", "language": "Arabic", "currency": "Moroccan dirham", "capital": "Rabat"},





    {"name": "Peru", "state": "South America", "demonym": "Peruvian", "language": "Spanish", "currency": "Sol", "capital": "Lima"},

    {"name": "Angola", "state": "Africa", "demonym": "Angolan", "language": "Portuguese", "currency": "Kwanza", "capital": "and largest city"},
    {"name": "Madagascar", "state": "Africa", "demonym": "Malagasy", "language": "", "currency": "Malagasy ariary", "capital": "and largest city"},
    {"name": "Ghana", "state": "Africa", "demonym": "Ghanaian", "language": "English", "currency": "Ghana cedi", "capital": "Accra"},
    {"name": "Australia", "state": "Oceania", "demonym": "", "language": "None", "currency": "Australian dollar", "capital": "Canberra"},
    {"name": "C", "state": "Europe", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Mozambique", "state": "Africa", "demonym": "Mozambican", "language": "Portuguese", "currency": "Mozambican metical", "capital": "and largest city"},
    {"name": "Niger", "state": "Africa", "demonym": "Nigerien", "language": "French", "currency": "West African CFA franc", "capital": "and largest city"},

    {"name": "Romania", "state": "Europe", "demonym": "Romanian", "language": "Romanian", "currency": "Romanian leu", "capital": "and largest city"},
    {"name": "Burkina Faso", "state": "Africa", "demonym": "", "language": "French", "currency": "West African CFA franc", "capital": "and largest city"},

    {"name": "Mali", "state": "Africa", "demonym": "Malian", "language": "French", "currency": "West African CFA franc", "capital": "and largest city"},
    {"name": "Chile", "state": "South America", "demonym": "Chilean", "language": "", "currency": "Peso", "capital": "and largest city"},
    {"name": "Malawi", "state": "Africa", "demonym": "Malawian", "language": "English", "currency": "Kwacha", "capital": "and largest city"},
    {"name": "Kazakhstan", "state": "Europe", "demonym": "Kazakh", "language": "", "currency": "Tenge", "capital": "Astana"},
    {"name": "Zambia", "state": "Africa", "demonym": "Zambian", "language": "English", "currency": "Zambian kwacha", "capital": "and largest city"},
    {"name": "Guatemala", "state": "North America", "demonym": "Guatemalan", "language": "Spanish", "currency": "Quetzal", "capital": "and largest city"},
    {"name": "Ecuador", "state": "South America", "demonym": "Ecuadorian", "language": "Spanish", "currency": "United States dollar", "capital": "Quito"},
    {"name": "Zimbabwe", "state": "Africa", "demonym": "Zimbabwean", "language": "", "currency": "United States dollar", "capital": "and largest city"},

    {"name": "Senegal", "state": "Africa", "demonym": "Senegalese", "language": "French", "currency": "CFA franc", "capital": "and largest city"},
    {"name": "Chad", "state": "Africa", "demonym": "Chadian", "language": "", "currency": "Central African CFA franc", "capital": "and largest city"},
    {"name": "Guinea", "state": "Africa", "demonym": "Guinean", "language": "French", "currency": "Guinean franc", "capital": "and largest city"},
    {"name": "South Sudan", "state": "Africa", "demonym": "South Sudanese", "language": "English", "currency": "South Sudanese pound", "capital": "and largest city"},
    {"name": "Rwanda", "state": "Africa", "demonym": "", "language": "", "currency": "Rwandan franc", "capital": "and largest city"},
    {"name": "Burundi", "state": "Africa", "demonym": "Burundian", "language": "", "currency": "Burundian franc", "capital": "and largest city"},
    {"name": "Tunisia", "state": "Africa", "demonym": "Tunisian", "language": "Arabic", "currency": "Tunisian dinar", "capital": "and largest city"},
    {"name": "Benin", "state": "Africa", "demonym": "", "language": "French", "currency": "West African CFA franc", "capital": "Porto-Novo"},
    {"name": "Belgium", "state": "Europe", "demonym": "Belgian", "language": "Dutch", "currency": "Euro", "capital": "Brussels"},
    {"name": "Somalia", "state": "Africa", "demonym": "", "language": "", "currency": "Somali shilling", "capital": "and largest city"},
    {"name": "Cuba", "state": "North America", "demonym": "Cuban", "language": "Spanish", "currency": "", "capital": "and largest city"},
    {"name": "Bolivia", "state": "South America", "demonym": "Bolivian", "language": "", "currency": "Boliviano", "capital": "Sucre"},
    {"name": "Haiti", "state": "North America", "demonym": "Haitian", "language": "", "currency": "Haitian gourde", "capital": "and largest city"},
    {"name": "Greece", "state": "Europe", "demonym": "", "language": "", "currency": "Euro", "capital": "and largest city"},
    {"name": "Dominican Republic", "state": "North America", "demonym": "Dominican", "language": "Spanish", "currency": "Peso", "capital": "and largest city"},
    {"name": "Czech Republic", "state": "Europe", "demonym": "Czech", "language": "", "currency": "Czech koruna", "capital": "and largest city"},
    {"name": "Portugal", "state": "Europe", "demonym": "Portuguese", "language": "Portuguese", "currency": "Euro", "capital": "and largest city"},
    {"name": "Azerbaijan", "state": "Europe", "demonym": "Azerbaijani", "language": "Azerbaijani", "currency": "Manat", "capital": "Baku"},
    {"name": "Sweden", "state": "Europe", "demonym": "", "language": "Swedish", "currency": "Swedish krona", "capital": "and largest city"},
    {"name": "Hungary", "state": "Europe", "demonym": "Hungarian", "language": "Hungarian", "currency": "Forint", "capital": "and largest city"},
    {"name": "Belarus", "state": "Europe", "demonym": "Belarusian", "language": "", "currency": "Belarusian ruble", "capital": "and largest city"},

    {"name": "Serbia", "state": "Europe", "demonym": "Serbian", "language": "Serbian", "currency": "Serbian dinar", "capital": "and largest city"},
    {"name": "Austria", "state": "Europe", "demonym": "Austrian", "language": "Austrian German", "currency": "Euro", "capital": "and largest city"},
    {"name": "Switzerland", "state": "Europe", "demonym": "English:", "language": "German", "currency": "Swiss franc", "capital": "None"},
    {"name": "Israel", "state": "Africa", "demonym": "Israeli", "language": "", "currency": "New shekel", "capital": "and largest city"},
    {"name": "Honduras", "state": "North America", "demonym": "", "language": "Spanish", "currency": "Lempira", "capital": "and largest city"},
    {"name": "Papua New Guinea", "state": "Oceania", "demonym": "Papua New Guinean", "language": "", "currency": "Papua New Guinean kina", "capital": "and largest city"},

    {"name": "Togo", "state": "Africa", "demonym": "Togolese", "language": "French", "currency": "CFA franc", "capital": "and largest city"},
    {"name": "Bulgaria", "state": "Europe", "demonym": "Bulgarian", "language": "Bulgarian", "currency": "Lev", "capital": "and largest city"},

    {"name": "Sierra Leone", "state": "Africa", "demonym": "Sierra Leonean", "language": "English", "currency": "Leone", "capital": "and largest city"},
    {"name": "Libya", "state": "Africa", "demonym": "Libyan", "language": "Arabic", "currency": "Libyan dinar", "capital": "and largest city"},
    {"name": "El Salvador", "state": "North America", "demonym": "Salvadoran", "language": "Spanish", "currency": "United States dollar", "capital": "and largest city"},

    {"name": "Denmark", "state": "Europe", "demonym": "", "language": "Danish", "currency": "Danish krone", "capital": "and largest city"},
    {"name": "Finland", "state": "Europe", "demonym": "", "language": "", "currency": "Euro", "capital": "and largest city"},

    {"name": "Eritrea", "state": "Africa", "demonym": "Eritrean", "language": "None", "currency": "Nakfa", "capital": "and largest city"},
    {"name": "Slovakia", "state": "Europe", "demonym": "Slovak", "language": "Slovak", "currency": "Euro (", "capital": "and largest city"},
    {"name": "Norway", "state": "Europe", "demonym": "Norwegian", "language": "Norwegian", "currency": "Norwegian krone", "capital": "and largest city"},
    {"name": "Central African Republic", "state": "Africa", "demonym": "Central African", "language": "French", "currency": "Central African CFA franc", "capital": "and largest city"},

    {"name": "Congo", "state": "Africa", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Ireland", "state": "Europe", "demonym": "Irish", "language": "", "currency": "", "capital": ""},

    {"name": "Liberia", "state": "Africa", "demonym": "Liberian", "language": "English", "currency": "Liberian dollar", "capital": "and largest city"},
    {"name": "New Zealand", "state": "Europe", "demonym": "New Zealander", "language": "", "currency": "New Zealand dollar", "capital": "Wellington"},
    {"name": "Mauritania", "state": "Africa", "demonym": "Mauritanian", "language": "Arabic", "currency": "Ouguiya", "capital": "and largest city"},
    {"name": "Croatia", "state": "Europe", "demonym": "", "language": "Croatian", "currency": "Kuna", "capital": "and largest city"},

    {"name": "Moldova", "state": "Europe", "demonym": "Moldovan", "language": "Romanian", "currency": "Leu", "capital": "and largest city"},
    {"name": "Panama", "state": "South America", "demonym": "Panamanian", "language": "Spanish", "currency": "", "capital": "and largest city"},
    {"name": "Georgia", "state": "", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Bosnia and Herzegovina", "state": "Europe", "demonym": "", "language": "", "currency": "Convertible mark", "capital": "and largest city"},
    {"name": "Uruguay", "state": "South America", "demonym": "Uruguayan", "language": "Spanish", "currency": "Uruguayan peso", "capital": "and largest city"},
    {"name": "Armenia", "state": "Europe", "demonym": "Armenian", "language": "Armenian", "currency": "Dram", "capital": "and largest city"},
    {"name": "Albania", "state": "Europe", "demonym": "Albanian", "language": "Albanian", "currency": "Lek", "capital": "and largest city"},
    {"name": "Lithuania", "state": "Europe", "demonym": "Lithuanian", "language": "Lithuanian", "currency": "Euro", "capital": "and largest city"},
    {"name": "Jamaica", "state": "Africa", "demonym": "Jamaican", "language": "English", "currency": "Jamaican dollar", "capital": "and largest city"},
    {"name": "Namibia", "state": "Africa", "demonym": "Namibian", "language": "English", "currency": "Namibian dollar", "capital": "and largest city"},
    {"name": "Botswana", "state": "Africa", "demonym": "", "language": "", "currency": "Pula", "capital": "and largest city"},

    {"name": "Lesotho", "state": "Africa", "demonym": "", "language": "", "currency": "Lesotho loti", "capital": "and largest city"},
    {"name": "Gambia", "state": "Africa", "demonym": "Gambian", "language": "English", "currency": "Dalasi", "capital": "Banjul"},
    {"name": "TFYR Macedonia", "state": "Europe", "demonym": "Macedonian", "language": "Macedonian", "currency": "Macedonian denar", "capital": "and largest city"},
    {"name": "Slovenia", "state": "Europe", "demonym": "Slovene", "language": "Slovene", "currency": "Euro", "capital": "and largest city"},
    {"name": "Latvia", "state": "Europe", "demonym": "Latvian", "language": "Latvian", "currency": "Euro", "capital": "and largest city"},
    {"name": "Guinea-Bissau", "state": "Africa", "demonym": "Bissau-Guinean", "language": "Portuguese", "currency": "West African CFA franc", "capital": "and largest city"},
    {"name": "Gabon", "state": "Africa", "demonym": "", "language": "French", "currency": "Central African CFA franc", "capital": "and largest city"},

    {"name": "Trinidad and Tobago", "state": "South America", "demonym": "Trinidadian (Trini)", "language": "English", "currency": "Trinidad and Tobago dollar", "capital": "Port of Spain"},
    {"name": "Swaziland", "state": "Africa", "demonym": "Swazi", "language": "", "currency": "South African rand", "capital": "Lobamba"},
    {"name": "Estonia", "state": "Europe", "demonym": "Estonian", "language": "Estonian", "currency": "Euro", "capital": "and largest city"},
    {"name": "Mauritius", "state": "Africa", "demonym": "Mauritian", "language": "None", "currency": "Mauritian rupee", "capital": "and largest city"},

    {"name": "Cyprus", "state": "Europe", "demonym": "Cypriot", "language": "", "currency": "Euro", "capital": "and largest city"},
    {"name": "Djibouti", "state": "Africa", "demonym": "Djiboutian", "language": "", "currency": "Djiboutian franc", "capital": "and largest city"},
    {"name": "Fiji", "state": "Oceania", "demonym": "Fijian", "language": "", "currency": "Fijian dollar", "capital": "Suva"},
    {"name": "Equatorial Guinea", "state": "Africa", "demonym": "", "language": "Spanish", "currency": "Central African CFA franc", "capital": "Malabo"},
    {"name": "Comoros", "state": "Africa", "demonym": "Comorian", "language": "", "currency": "Comorian franc", "capital": "and largest city"},

    {"name": "Guyana", "state": "South America", "demonym": "Guyanese", "language": "English", "currency": "Guyanese dollar", "capital": "and largest city"},
    {"name": "Montenegro", "state": "Europe", "demonym": "Montenegrin", "language": "Montenegrin", "currency": "Euro", "capital": "and largest city"},
    {"name": "Solomon Islands", "state": "Oceania", "demonym": "Solomon Islander", "language": "English", "currency": "Solomon Islands dollar", "capital": "and largest city"},
    {"name": "Luxembourg", "state": "Europe", "demonym": "Luxembourgish,", "language": "French", "currency": "Euro", "capital": "and largest city"},
    {"name": "Suriname", "state": "South America", "demonym": "Surinamese", "language": "Dutch", "currency": "Surinamese dollar", "capital": "and largest city"},
    {"name": "Cabo Verde", "state": "Africa", "demonym": "Cape Verdean", "language": "Portuguese", "currency": "Cape Verdean escudo", "capital": "and largest city"},

    {"name": "Malta", "state": "Europe", "demonym": "Maltese", "language": "Maltese", "currency": "Euro (", "capital": "Valletta"},
    {"name": "Bahamas", "state": "North America", "demonym": "Bahamian", "language": "English", "currency": "Bahamian dollar", "capital": "and largest city"},

    {"name": "Iceland", "state": "", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Barbados", "state": "North America", "demonym": "", "language": "English", "currency": "Bajan dollar", "capital": "and largest city"},
    {"name": "Vanuatu", "state": "Oceania", "demonym": "Ni-Vanuatu", "language": "", "currency": "Vanuatu vatu", "capital": "and largest city"},
    {"name": "Sao Tome and Principe", "state": "Africa", "demonym": "", "language": "Portuguese", "currency": "Dobra", "capital": "and largest city"},
    {"name": "Samoa", "state": "Oceania", "demonym": "Samoan", "language": "", "currency": "Tala", "capital": "and largest city"},
    {"name": "Saint Lucia", "state": "North America", "demonym": "Saint Lucian", "language": "English", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Kiribati", "state": "Oceania", "demonym": "I-Kiribati", "language": "", "currency": "Kiribati dollar", "capital": "and largest city"},
    {"name": "St. Vincent", "state": "Europe", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Grenada", "state": "North America", "demonym": "Grenadian", "language": "", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Tonga", "state": "Europe", "demonym": "Tongan", "language": "", "currency": "Pa", "capital": "and largest city"},
    {"name": "Micronesia", "state": "Oceania", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Seychelles", "state": "Africa", "demonym": "", "language": "", "currency": "Seychellois rupee", "capital": "and largest city"},
    {"name": "Antigua and Barbuda", "state": "North America", "demonym": "Antiguan", "language": "English", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Dominica", "state": "North America", "demonym": "Dominican", "language": "English", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Andorra", "state": "Europe", "demonym": "Andorran", "language": "Catalan", "currency": "Euro", "capital": "and largest city"},
    {"name": "Saint Kitts and Nevis", "state": "North America", "demonym": "Kittitian or Nevisian", "language": "English", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Marshall Islands", "state": "Oceania", "demonym": "Marshallese", "language": "", "currency": "United States dollar", "capital": "and largest city"},
    {"name": "Liechtenstein", "state": "Europe", "demonym": "", "language": "German", "currency": "Swiss franc", "capital": "Vaduz"},
    {"name": "Monaco", "state": "Europe", "demonym": "", "language": "French", "currency": "Euro", "capital": "Monaco-ville"},
    {"name": "San Marino", "state": "Europe", "demonym": "Sammarinese", "language": "Italian", "currency": "Euro", "capital": "City of San Marino"},
    {"name": "Palau", "state": "Oceania", "demonym": "Palauan", "language": "English", "currency": "United States dollar", "capital": "Ngerulmud"},
    {"name": "Nauru", "state": "Oceania", "demonym": "Nauruan", "language": "", "currency": "Australian dollar", "capital": "Yaren"},
    {"name": "Tuvalu", "state": "Oceania", "demonym": "Tuvaluan", "language": "", "currency": "Tuvaluan dollar", "capital": "Funafuti"},
    {"name": "Holy See", "state": "Europe", "demonym": "", "language": "", "currency": "", "capital": ""},
]

countries_list = ['China', 'India', 'U.S.', 'Indonesia', 'Brazil', 'Pakistan', 'Nigeria', 'Bangladesh', 'Russia', 'Mexico', 'Japan', 'Ethiopia', 'Philippines', 'Viet Nam', 'Egypt', 'DR Congo', 'Iran', 'Germany', 'Turkey', 'Thailand', 'U.K.', 'France', 'Italy', 'Tanzania', 'South Africa', 'Myanmar', 'South Korea', 'Colombia', 'Kenya', 'Spain', 'Ukraine', 'Argentina', 'Sudan', 'Uganda', 'Algeria', 'Iraq', 'Poland', 'Canada', 'Morocco', 'Afghanistan', 'Saudi Arabia', 'Peru', 'Venezuela', 'Malaysia', 'Uzbekistan', 'Mozambique', 'Nepal', 'Ghana', 'Yemen', 'Angola', 'Madagascar', 'North Korea', 'Australia', 'Cameroon', 'C', 'Niger', 'Sri Lanka', 'Romania', 'Burkina Faso', 'Syria', 'Mali', 'Chile', 'Malawi', 'Kazakhstan', 'Zambia', 'Netherlands', 'Guatemala', 'Ecuador', 'Zimbabwe', 'Cambodia', 'Senegal', 'Chad', 'Guinea', 'South Sudan', 'Rwanda', 'Burundi', 'Tunisia', 'Benin', 'Belgium', 'Somalia', 'Cuba', 'Bolivia', 'Haiti', 'Greece', 'Dominican Republic', 'Czech Republic', 'Portugal', 'Azerbaijan', 'Sweden', 'Hungary', 'Belarus', 'United Arab Emirates', 'Tajikistan', 'Serbia', 'Austria', 'Switzerland', 'Israel', 'Honduras', 'Papua New Guinea', 'Jordan', 'Togo', 'Bulgaria', 'Laos', 'Paraguay', 'Sierra Leone', 'Libya', 'Nicaragua', 'El Salvador', 'Kyrgyzstan', 'Lebanon', 'Singapore', 'Denmark', 'Finland', 'Turkmenistan', 'Eritrea', 'Slovakia', 'Norway', 'Central African Republic', 'State of Palestine', 'Costa Rica', 'Congo', 'Ireland', 'Oman', 'Liberia', 'New Zealand', 'Mauritania', 'Croatia', 'Kuwait', 'Moldova', 'Panama', 'Georgia', 'Bosnia and Herzegovina', 'Uruguay', 'Mongolia', 'Armenia', 'Albania', 'Lithuania', 'Jamaica', 'Namibia', 'Botswana', 'Qatar', 'Lesotho', 'Gambia', 'TFYR Macedonia', 'Slovenia', 'Latvia', 'Guinea-Bissau', 'Gabon', 'Bahrain', 'Trinidad and Tobago', 'Swaziland', 'Estonia', 'Mauritius', 'Timor-Leste', 'Cyprus', 'Djibouti', 'Fiji', 'Equatorial Guinea', 'Comoros', 'Bhutan', 'Guyana', 'Montenegro', 'Solomon Islands', 'Luxembourg', 'Suriname', 'Cabo Verde', 'Brunei', 'Malta', 'Bahamas', 'Maldives', 'Belize', 'Iceland', 'Barbados', 'Vanuatu', 'Sao Tome and Principe', 'Samoa', 'Saint Lucia', 'Kiribati', 'St. Vincent', 'Grenada', 'Tonga', 'Micronesia', 'Seychelles', 'Antigua and Barbuda', 'Dominica', 'Andorra', 'Saint Kitts and Nevis', 'Marshall Islands', 'Liechtenstein', 'Monaco', 'San Marino', 'Palau', 'Nauru', 'Tuvalu', 'Holy See']
