# -*- coding:utf-8 -*-

questions = [
    # {'name': '','state': '', 'demonym': '','language': '','currency': '','capital': '',},
    # {'name': 'China','demonym': 'Chinese','state': 'Asia','language': 'Chinese','currency': 'RMB','capital': 'BeiJing',},
    # {'name': 'Indonesia','demonym': 'Indonesian','state': 'Asia','language': 'Indonesian','currency': 'rupiah','capital': 'Jakarta',},
    # {'name': 'Germany','state': 'Europe','capital': 'Berlin','language': 'German','demonym': 'German','currency': 'Euro',},
    # {'name': 'Canada','state': 'North America','capital': 'Ottawa','language': 'English and French','demonym': 'Canadian','currency': 'Canadian dollar',},
    # {'name': 'Iran','state': 'Asia','capital': 'Tehran','language': 'Persian','demonym': 'Iranian','currency': 'Rial',},
    # {'name': 'Thailand','demonym': 'Thai','state': 'Asia','language': 'Thai','currency': 'Baht','capital': 'Bangkok',},
    # {'name': 'Chile','demonym': 'Chilean','state': 'South American','language': 'Spanish','currency': 'Peso','capital': 'Santiago',},
    # {'name': 'Brazil','demonym': 'Brazilian','state': 'South America','language': 'Portuguese','currency': 'Real','capital': u'Brasília',},
    # {'name': 'Netherlands','demonym': '	Dutch','state': 'Europe','language': 'Dutch','currency': 'Euro','capital': 'Amsterdam',},
    # {'name': 'Malaysia','state': 'Asia', 'demonym': 'Malaysian','language': 'Malaysia','currency': 'Ringgit','capital': 'Kuala Lumpur',},

    # checked
    {"name": "China", "state": "Asia", "demonym": "Chinese", "language": "Chinese", "currency": "Renminbi", "capital": "Beijing"},
    {"name": "India", "state": "Asia", "demonym": "Indian", "language": "Hindi", "currency": "rupee", "capital": "New Delhi"},
    {"name": "U.S.", "state": "North America", "demonym": "American", "language": "English", "currency": "dollar", "capital": "Washington, D.C."},
    {"name": "Indonesia", "state": "Asia", "demonym": "Indonesian", "language": "Indonesian", "currency": "rupiah", "capital": "Jakarta"},
    {"name": "Pakistan", "state": "Asia", "demonym": "Pakistani", "language": "Urdu", "currency": "rupee", "capital": "Islamabad"},
    {"name": "Nigeria", "state": "Africa", "demonym": "Nigerian", "language": "English", "currency": "Naira", "capital": "Abuja"},
    {"name": "Bangladesh", "state": "Asia", "demonym": "Bangladeshi", "language": "Bengali", "currency": "Taka", "capital": "Dhaka"},
    {"name": "Russia", "state": "Europe", "demonym": "Russian", "language": "Russian", "currency": "ruble", "capital": "Moscow"},

    {"name": "Mexico", "state": "North America", "demonym": "Mexican", "language": "None at", "currency": "Peso", "capital": "and largest city"},
    {"name": "Japan", "state": "Asia", "demonym": "Japanese", "language": "None", "currency": "Yen", "capital": "and largest city"},
    {"name": "Ethiopia", "state": "Africa", "demonym": "Ethiopian", "language": "All Ethiopian languages", "currency": "Birr", "capital": "and largest city"},
    {"name": "Philippines", "state": "Asia", "demonym": "", "language": "", "currency": "Peso", "capital": "Manila"},
    {"name": "Egypt", "state": "Africa", "demonym": "Egyptian", "language": "Arabic", "currency": "Egyptian pound", "capital": "and largest city"},
    {"name": "DR Congo", "state": "Africa", "demonym": "Congolese", "language": "French", "currency": "Congolese franc", "capital": "and largest city"},
    {"name": "Iran", "state": "Asia", "demonym": "Iranian, Persian", "language": "Persian", "currency": "Rial", "capital": "and largest city"},
    {"name": "Germany", "state": "Europe", "demonym": "German", "language": "German", "currency": "Euro", "capital": "and largest city"},
    {"name": "Turkey", "state": "Europe", "demonym": "", "language": "Turkish", "currency": "Turkish lira", "capital": "Ankara"},
    {"name": "Thailand", "state": "Asia", "demonym": "Thai", "language": "Thai", "currency": "Baht", "capital": "and largest city"},
    {"name": "U.K.", "state": "Europe", "demonym": "", "language": "", "currency": "Pound", "capital": "and largest city"},
    {"name": "France", "state": "Europe", "demonym": "French", "language": "", "currency": "", "capital": "and largest city"},
    {"name": "Italy", "state": "Europe", "demonym": "Italian", "language": "Italian", "currency": "Euro (", "capital": "and largest city"},
    {"name": "Tanzania", "state": "Africa", "demonym": "Tanzanian", "language": "none de jure", "currency": "Tanzanian shilling", "capital": "Dodoma"},
    {"name": "South Africa", "state": "Africa", "demonym": "South African", "language": "", "currency": "South African rand", "capital": ""},
    {"name": "Myanmar", "state": "Asia", "demonym": "Burmese/Myanma", "language": "Burmese", "currency": "Kyat", "capital": "Naypyidaw"},
    {"name": "South Korea", "state": "Asia", "demonym": "", "language": "Korean", "currency": "South Korean won", "capital": "and largest city"},
    {"name": "Colombia", "state": "South America", "demonym": "Colombian", "language": "Spanish", "currency": "Peso", "capital": "and largest city"},
    {"name": "Kenya", "state": "Africa", "demonym": "Kenyan", "language": "", "currency": "Kenyan shilling", "capital": "and largest city"},
    {"name": "Spain", "state": "Europe", "demonym": "", "language": "", "currency": "Euro", "capital": "and largest city"},
    {"name": "Ukraine", "state": "Europe", "demonym": "Ukrainian", "language": "Ukrainian", "currency": "Ukrainian hryvnia", "capital": "and largest city"},
    {"name": "Argentina", "state": "South America", "demonym": "", "language": "", "currency": "Peso", "capital": "and largest city"},
    {"name": "Sudan", "state": "Africa", "demonym": "Sudanese", "language": "", "currency": "Sudanese pound", "capital": "Khartoum"},
    {"name": "Uganda", "state": "Africa", "demonym": "Ugandan", "language": "English", "currency": "Ugandan shilling", "capital": "and largest city"},
    {"name": "Algeria", "state": "Africa", "demonym": "Algerian", "language": "", "currency": "Dinar", "capital": "and largest city"},
    {"name": "Iraq", "state": "Asia", "demonym": "Iraqi", "language": "", "currency": "Iraqi dinar", "capital": "and largest city"},
    {"name": "Canada", "state": "North America", "demonym": "Canadian", "language": "", "currency": "Canadian dollar", "capital": "Ottawa"},
    {"name": "Morocco", "state": "Africa", "demonym": "Moroccan", "language": "", "currency": "Moroccan dirham", "capital": "Rabat"},
    {"name": "Afghanistan", "state": "Asia", "demonym": "Afghan", "language": "", "currency": "Afghani", "capital": "and largest city"},
    {"name": "Saudi Arabia", "state": "Asia", "demonym": "", "language": "Arabic", "currency": "Saudi riyal", "capital": "and largest city"},
    {"name": "Peru", "state": "South America", "demonym": "Peruvian", "language": "", "currency": "Sol", "capital": "and largest city"},
    {"name": "Malaysia", "state": "Asia", "demonym": "Malaysian", "language": "Bahasa Malaysia", "currency": "Ringgit", "capital": "Kuala Lumpur"},
    {"name": "Uzbekistan", "state": "Asia", "demonym": "Uzbek", "language": "Uzbek", "currency": "Uzbekistan som", "capital": "and largest city"},
    {"name": "Mozambique", "state": "Africa", "demonym": "Mozambican", "language": "Portuguese", "currency": "Mozambican metical", "capital": "and largest city"},
    {"name": "Nepal", "state": "Asia", "demonym": "Nepali", "language": "Nepali", "currency": "Nepalese rupee", "capital": "and largest city"},
    {"name": "Ghana", "state": "Africa", "demonym": "Ghanaian", "language": "English", "currency": "Ghana cedi", "capital": "Accra"},
    {"name": "Yemen", "state": "Asia", "demonym": "Yemeni, Yemenite", "language": "Arabic", "currency": "Yemeni rial", "capital": "Sana'a"},
    {"name": "Angola", "state": "Africa", "demonym": "Angolan", "language": "Portuguese", "currency": "Kwanza", "capital": "and largest city"},
    {"name": "Madagascar", "state": "Africa", "demonym": "Malagasy", "language": "", "currency": "Malagasy ariary", "capital": "and largest city"},
    {"name": "North Korea", "state": "Asia", "demonym": "", "language": "Korean", "currency": "North Korean won", "capital": "and largest city"},
    {"name": "Australia", "state": "Oceania", "demonym": "", "language": "None", "currency": "Australian dollar", "capital": "Canberra"},
    {"name": "C", "state": "Europe", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Niger", "state": "Africa", "demonym": "Nigerien", "language": "French", "currency": "West African CFA franc", "capital": "and largest city"},
    {"name": "Sri Lanka", "state": "Asia", "demonym": "Sri Lankan", "language": "", "currency": "Sri Lankan rupee", "capital": "Sri Jayawardenepura Kotte"},
    {"name": "Romania", "state": "Europe", "demonym": "Romanian", "language": "Romanian", "currency": "Romanian leu", "capital": "and largest city"},
    {"name": "Burkina Faso", "state": "Africa", "demonym": "", "language": "French", "currency": "West African CFA franc", "capital": "and largest city"},
    {"name": "Syria", "state": "Asia", "demonym": "", "language": "Arabic", "currency": "Syrian pound", "capital": "and largest city"},
    {"name": "Mali", "state": "Africa", "demonym": "Malian", "language": "French", "currency": "West African CFA franc", "capital": "and largest city"},
    {"name": "Chile", "state": "South America", "demonym": "Chilean", "language": "", "currency": "Peso", "capital": "and largest city"},
    {"name": "Malawi", "state": "Africa", "demonym": "Malawian", "language": "English", "currency": "Kwacha", "capital": "and largest city"},
    {"name": "Kazakhstan", "state": "Europe", "demonym": "Kazakh", "language": "", "currency": "Tenge", "capital": "Astana"},
    {"name": "Zambia", "state": "Africa", "demonym": "Zambian", "language": "English", "currency": "Zambian kwacha", "capital": "and largest city"},
    {"name": "Guatemala", "state": "North America", "demonym": "Guatemalan", "language": "Spanish", "currency": "Quetzal", "capital": "and largest city"},
    {"name": "Ecuador", "state": "South America", "demonym": "Ecuadorian", "language": "Spanish", "currency": "United States dollar", "capital": "Quito"},
    {"name": "Zimbabwe", "state": "Africa", "demonym": "Zimbabwean", "language": "", "currency": "United States dollar", "capital": "and largest city"},
    {"name": "Cambodia", "state": "Asia", "demonym": "Cambodian, Kampuchean", "language": "Khmer", "currency": "Riel", "capital": "and largest city"},
    {"name": "Senegal", "state": "Africa", "demonym": "Senegalese", "language": "French", "currency": "CFA franc", "capital": "and largest city"},
    {"name": "Chad", "state": "Africa", "demonym": "Chadian", "language": "", "currency": "Central African CFA franc", "capital": "and largest city"},
    {"name": "Guinea", "state": "Africa", "demonym": "Guinean", "language": "French", "currency": "Guinean franc", "capital": "and largest city"},
    {"name": "South Sudan", "state": "Africa", "demonym": "South Sudanese", "language": "English", "currency": "South Sudanese pound", "capital": "and largest city"},
    {"name": "Rwanda", "state": "Africa", "demonym": "", "language": "", "currency": "Rwandan franc", "capital": "and largest city"},
    {"name": "Burundi", "state": "Africa", "demonym": "Burundian", "language": "", "currency": "Burundian franc", "capital": "and largest city"},
    {"name": "Tunisia", "state": "Africa", "demonym": "Tunisian", "language": "Arabic", "currency": "Tunisian dinar", "capital": "and largest city"},
    {"name": "Benin", "state": "Africa", "demonym": "", "language": "French", "currency": "West African CFA franc", "capital": "Porto-Novo"},
    {"name": "Belgium", "state": "Europe", "demonym": "Belgian", "language": "Dutch", "currency": "Euro", "capital": "Brussels"},
    {"name": "Somalia", "state": "Africa", "demonym": "", "language": "", "currency": "Somali shilling", "capital": "and largest city"},
    {"name": "Cuba", "state": "North America", "demonym": "Cuban", "language": "Spanish", "currency": "", "capital": "and largest city"},
    {"name": "Bolivia", "state": "South America", "demonym": "Bolivian", "language": "", "currency": "Boliviano", "capital": "Sucre"},
    {"name": "Haiti", "state": "North America", "demonym": "Haitian", "language": "", "currency": "Haitian gourde", "capital": "and largest city"},
    {"name": "Greece", "state": "Europe", "demonym": "", "language": "", "currency": "Euro", "capital": "and largest city"},
    {"name": "Dominican Republic", "state": "North America", "demonym": "Dominican", "language": "Spanish", "currency": "Peso", "capital": "and largest city"},
    {"name": "Czech Republic", "state": "Europe", "demonym": "Czech", "language": "", "currency": "Czech koruna", "capital": "and largest city"},
    {"name": "Portugal", "state": "Europe", "demonym": "Portuguese", "language": "Portuguese", "currency": "Euro", "capital": "and largest city"},
    {"name": "Azerbaijan", "state": "Europe", "demonym": "Azerbaijani", "language": "Azerbaijani", "currency": "Manat", "capital": "Baku"},
    {"name": "Sweden", "state": "Europe", "demonym": "", "language": "Swedish", "currency": "Swedish krona", "capital": "and largest city"},
    {"name": "Hungary", "state": "Europe", "demonym": "Hungarian", "language": "Hungarian", "currency": "Forint", "capital": "and largest city"},
    {"name": "Belarus", "state": "Europe", "demonym": "Belarusian", "language": "", "currency": "Belarusian ruble", "capital": "and largest city"},
    {"name": "United Arab Emirates", "state": "Asia", "demonym": "", "language": "Arabic", "currency": "UAE dirham", "capital": "Abu Dhabi"},
    {"name": "Tajikistan", "state": "Asia", "demonym": "Tajik", "language": "Tajik", "currency": "Somoni", "capital": "and largest city"},
    {"name": "Serbia", "state": "Europe", "demonym": "Serbian", "language": "Serbian", "currency": "Serbian dinar", "capital": "and largest city"},
    {"name": "Austria", "state": "Europe", "demonym": "Austrian", "language": "Austrian German", "currency": "Euro", "capital": "and largest city"},
    {"name": "Switzerland", "state": "Europe", "demonym": "English:", "language": "German", "currency": "Swiss franc", "capital": "None"},
    {"name": "Israel", "state": "Africa", "demonym": "Israeli", "language": "", "currency": "New shekel", "capital": "and largest city"},
    {"name": "Honduras", "state": "North America", "demonym": "", "language": "Spanish", "currency": "Lempira", "capital": "and largest city"},
    {"name": "Papua New Guinea", "state": "Oceania", "demonym": "Papua New Guinean", "language": "", "currency": "Papua New Guinean kina", "capital": "and largest city"},
    {"name": "Jordan", "state": "Asia", "demonym": "Jordanian", "language": "Arabic", "currency": "Dinar", "capital": "and largest city"},
    {"name": "Togo", "state": "Africa", "demonym": "Togolese", "language": "French", "currency": "CFA franc", "capital": "and largest city"},
    {"name": "Bulgaria", "state": "Europe", "demonym": "Bulgarian", "language": "Bulgarian", "currency": "Lev", "capital": "and largest city"},
    {"name": "Laos", "state": "Asia", "demonym": "Laotian", "language": "Lao", "currency": "Kip", "capital": "and largest city"},
    {"name": "Sierra Leone", "state": "Africa", "demonym": "Sierra Leonean", "language": "English", "currency": "Leone", "capital": "and largest city"},
    {"name": "Libya", "state": "Africa", "demonym": "Libyan", "language": "Arabic", "currency": "Libyan dinar", "capital": "and largest city"},
    {"name": "El Salvador", "state": "North America", "demonym": "Salvadoran", "language": "Spanish", "currency": "United States dollar", "capital": "and largest city"},
    {"name": "Kyrgyzstan", "state": "Asia", "demonym": "", "language": "", "currency": "Som", "capital": "and largest city"},
    {"name": "Lebanon", "state": "Asia", "demonym": "Lebanese", "language": "Arabic", "currency": "Lebanese pound", "capital": "and largest city"},
    {"name": "Singapore", "state": "Asia", "demonym": "Singaporean", "language": "", "currency": "Singapore dollar", "capital": "Singapore"},
    {"name": "Denmark", "state": "Europe", "demonym": "", "language": "Danish", "currency": "Danish krone", "capital": "and largest city"},
    {"name": "Finland", "state": "Europe", "demonym": "", "language": "", "currency": "Euro", "capital": "and largest city"},
    {"name": "Turkmenistan", "state": "Asia", "demonym": "Turkmen", "language": "Turkmen", "currency": "Turkmen new manat", "capital": "and largest city"},
    {"name": "Eritrea", "state": "Africa", "demonym": "Eritrean", "language": "None", "currency": "Nakfa", "capital": "and largest city"},
    {"name": "Slovakia", "state": "Europe", "demonym": "Slovak", "language": "Slovak", "currency": "Euro (", "capital": "and largest city"},
    {"name": "Norway", "state": "Europe", "demonym": "Norwegian", "language": "Norwegian", "currency": "Norwegian krone", "capital": "and largest city"},
    {"name": "Central African Republic", "state": "Africa", "demonym": "Central African", "language": "French", "currency": "Central African CFA franc", "capital": "and largest city"},
    {"name": "State of Palestine", "state": "Asia", "demonym": "Palestinian", "language": "Arabic", "currency": "", "capital": ""},
    {"name": "Congo", "state": "Africa", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Ireland", "state": "Europe", "demonym": "Irish", "language": "", "currency": "", "capital": ""},
    {"name": "Oman", "state": "Asia", "demonym": "Omani", "language": "Arabic", "currency": "Rial", "capital": "and largest city"},
    {"name": "Liberia", "state": "Africa", "demonym": "Liberian", "language": "English", "currency": "Liberian dollar", "capital": "and largest city"},
    {"name": "New Zealand", "state": "Europe", "demonym": "New Zealander", "language": "", "currency": "New Zealand dollar", "capital": "Wellington"},
    {"name": "Mauritania", "state": "Africa", "demonym": "Mauritanian", "language": "Arabic", "currency": "Ouguiya", "capital": "and largest city"},
    {"name": "Croatia", "state": "Europe", "demonym": "", "language": "Croatian", "currency": "Kuna", "capital": "and largest city"},
    {"name": "Kuwait", "state": "Asia", "demonym": "Kuwaiti", "language": "Arabic", "currency": "Kuwaiti dinar", "capital": "and largest city"},
    {"name": "Moldova", "state": "Europe", "demonym": "Moldovan", "language": "Romanian", "currency": "Leu", "capital": "and largest city"},
    {"name": "Panama", "state": "South America", "demonym": "Panamanian", "language": "Spanish", "currency": "", "capital": "and largest city"},
    {"name": "Georgia", "state": "", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Bosnia and Herzegovina", "state": "Europe", "demonym": "", "language": "", "currency": "Convertible mark", "capital": "and largest city"},
    {"name": "Uruguay", "state": "South America", "demonym": "Uruguayan", "language": "Spanish", "currency": "Uruguayan peso", "capital": "and largest city"},
    {"name": "Armenia", "state": "Europe", "demonym": "Armenian", "language": "Armenian", "currency": "Dram", "capital": "and largest city"},
    {"name": "Albania", "state": "Europe", "demonym": "Albanian", "language": "Albanian", "currency": "Lek", "capital": "and largest city"},
    {"name": "Lithuania", "state": "Europe", "demonym": "Lithuanian", "language": "Lithuanian", "currency": "Euro", "capital": "and largest city"},
    {"name": "Jamaica", "state": "Africa", "demonym": "Jamaican", "language": "English", "currency": "Jamaican dollar", "capital": "and largest city"},
    {"name": "Namibia", "state": "Africa", "demonym": "Namibian", "language": "English", "currency": "Namibian dollar", "capital": "and largest city"},
    {"name": "Botswana", "state": "Africa", "demonym": "", "language": "", "currency": "Pula", "capital": "and largest city"},
    {"name": "Qatar", "state": "Asia", "demonym": "Qatari", "language": "Arabic", "currency": "Riyal", "capital": "and largest city"},
    {"name": "Lesotho", "state": "Africa", "demonym": "", "language": "", "currency": "Lesotho loti", "capital": "and largest city"},
    {"name": "Gambia", "state": "Africa", "demonym": "Gambian", "language": "English", "currency": "Dalasi", "capital": "Banjul"},
    {"name": "TFYR Macedonia", "state": "Europe", "demonym": "Macedonian", "language": "Macedonian", "currency": "Macedonian denar", "capital": "and largest city"},
    {"name": "Slovenia", "state": "Europe", "demonym": "Slovene", "language": "Slovene", "currency": "Euro", "capital": "and largest city"},
    {"name": "Latvia", "state": "Europe", "demonym": "Latvian", "language": "Latvian", "currency": "Euro", "capital": "and largest city"},
    {"name": "Guinea-Bissau", "state": "Africa", "demonym": "Bissau-Guinean", "language": "Portuguese", "currency": "West African CFA franc", "capital": "and largest city"},
    {"name": "Gabon", "state": "Africa", "demonym": "", "language": "French", "currency": "Central African CFA franc", "capital": "and largest city"},
    {"name": "Bahrain", "state": "Asia", "demonym": "Bahraini", "language": "Arabic", "currency": "Bahraini dinar", "capital": "and largest city"},
    {"name": "Trinidad and Tobago", "state": "South America", "demonym": "Trinidadian (Trini)", "language": "English", "currency": "Trinidad and Tobago dollar", "capital": "Port of Spain"},
    {"name": "Swaziland", "state": "Africa", "demonym": "Swazi", "language": "", "currency": "South African rand", "capital": "Lobamba"},
    {"name": "Estonia", "state": "Europe", "demonym": "Estonian", "language": "Estonian", "currency": "Euro", "capital": "and largest city"},
    {"name": "Mauritius", "state": "Africa", "demonym": "Mauritian", "language": "None", "currency": "Mauritian rupee", "capital": "and largest city"},
    {"name": "Timor-Leste", "state": "Asia", "demonym": "East Timorese", "language": "", "currency": "United States Dollar", "capital": "and largest city"},
    {"name": "Cyprus", "state": "Europe", "demonym": "Cypriot", "language": "", "currency": "Euro", "capital": "and largest city"},
    {"name": "Djibouti", "state": "Africa", "demonym": "Djiboutian", "language": "", "currency": "Djiboutian franc", "capital": "and largest city"},
    {"name": "Fiji", "state": "Oceania", "demonym": "Fijian", "language": "", "currency": "Fijian dollar", "capital": "Suva"},
    {"name": "Equatorial Guinea", "state": "Africa", "demonym": "", "language": "Spanish", "currency": "Central African CFA franc", "capital": "Malabo"},
    {"name": "Comoros", "state": "Africa", "demonym": "Comorian", "language": "", "currency": "Comorian franc", "capital": "and largest city"},
    {"name": "Bhutan", "state": "Asia", "demonym": "Bhutanese", "language": "Dzongkha", "currency": "Ngultrum", "capital": "and largest city"},
    {"name": "Guyana", "state": "South America", "demonym": "Guyanese", "language": "English", "currency": "Guyanese dollar", "capital": "and largest city"},
    {"name": "Montenegro", "state": "Europe", "demonym": "Montenegrin", "language": "Montenegrin", "currency": "Euro", "capital": "and largest city"},
    {"name": "Solomon Islands", "state": "Oceania", "demonym": "Solomon Islander", "language": "English", "currency": "Solomon Islands dollar", "capital": "and largest city"},
    {"name": "Luxembourg", "state": "Europe", "demonym": "Luxembourgish,", "language": "French", "currency": "Euro", "capital": "and largest city"},
    {"name": "Suriname", "state": "South America", "demonym": "Surinamese", "language": "Dutch", "currency": "Surinamese dollar", "capital": "and largest city"},
    {"name": "Cabo Verde", "state": "Africa", "demonym": "Cape Verdean", "language": "Portuguese", "currency": "Cape Verdean escudo", "capital": "and largest city"},
    {"name": "Brunei", "state": "Asia", "demonym": "Bruneian", "language": "Malay", "currency": "Brunei dollar", "capital": "and largest city"},
    {"name": "Malta", "state": "Europe", "demonym": "Maltese", "language": "Maltese", "currency": "Euro (", "capital": "Valletta"},
    {"name": "Bahamas", "state": "North America", "demonym": "Bahamian", "language": "English", "currency": "Bahamian dollar", "capital": "and largest city"},
    {"name": "Maldives", "state": "Asia", "demonym": "Maldivian", "language": "Maldivian (Dhivehi)", "currency": "Maldivian rufiyaa", "capital": "and largest city"},
    {"name": "Belize", "state": "Asia", "demonym": "Belizean", "language": "English", "currency": "Belize dollar", "capital": "Belmopan"},
    {"name": "Iceland", "state": "", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Barbados", "state": "North America", "demonym": "", "language": "English", "currency": "Bajan dollar", "capital": "and largest city"},
    {"name": "Vanuatu", "state": "Oceania", "demonym": "Ni-Vanuatu", "language": "", "currency": "Vanuatu vatu", "capital": "and largest city"},
    {"name": "Sao Tome and Principe", "state": "Africa", "demonym": "", "language": "Portuguese", "currency": "Dobra", "capital": "and largest city"},
    {"name": "Samoa", "state": "Oceania", "demonym": "Samoan", "language": "", "currency": "Tala", "capital": "and largest city"},
    {"name": "Saint Lucia", "state": "North America", "demonym": "Saint Lucian", "language": "English", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Kiribati", "state": "Oceania", "demonym": "I-Kiribati", "language": "", "currency": "Kiribati dollar", "capital": "and largest city"},
    {"name": "St. Vincent", "state": "Europe", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Grenada", "state": "North America", "demonym": "Grenadian", "language": "", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Tonga", "state": "Europe", "demonym": "Tongan", "language": "", "currency": "Pa", "capital": "and largest city"},
    {"name": "Micronesia", "state": "Oceania", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Seychelles", "state": "Africa", "demonym": "", "language": "", "currency": "Seychellois rupee", "capital": "and largest city"},
    {"name": "Antigua and Barbuda", "state": "North America", "demonym": "Antiguan", "language": "English", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Dominica", "state": "North America", "demonym": "Dominican", "language": "English", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Andorra", "state": "Europe", "demonym": "Andorran", "language": "Catalan", "currency": "Euro", "capital": "and largest city"},
    {"name": "Saint Kitts and Nevis", "state": "North America", "demonym": "Kittitian or Nevisian", "language": "English", "currency": "East Caribbean dollar", "capital": "and largest city"},
    {"name": "Marshall Islands", "state": "Oceania", "demonym": "Marshallese", "language": "", "currency": "United States dollar", "capital": "and largest city"},
    {"name": "Liechtenstein", "state": "Europe", "demonym": "", "language": "German", "currency": "Swiss franc", "capital": "Vaduz"},
    {"name": "Monaco", "state": "Europe", "demonym": "", "language": "French", "currency": "Euro", "capital": "Monaco-ville"},
    {"name": "San Marino", "state": "Europe", "demonym": "Sammarinese", "language": "Italian", "currency": "Euro", "capital": "City of San Marino"},
    {"name": "Palau", "state": "Oceania", "demonym": "Palauan", "language": "English", "currency": "United States dollar", "capital": "Ngerulmud"},
    {"name": "Nauru", "state": "Oceania", "demonym": "Nauruan", "language": "", "currency": "Australian dollar", "capital": "Yaren"},
    {"name": "Tuvalu", "state": "Oceania", "demonym": "Tuvaluan", "language": "", "currency": "Tuvaluan dollar", "capital": "Funafuti"},
    {"name": "Holy See", "state": "Europe", "demonym": "", "language": "", "currency": "", "capital": ""},
]

countries_list = ['China', 'India', 'U.S.', 'Indonesia', 'Brazil', 'Pakistan', 'Nigeria', 'Bangladesh', 'Russia', 'Mexico', 'Japan', 'Ethiopia', 'Philippines', 'Viet Nam', 'Egypt', 'DR Congo', 'Iran', 'Germany', 'Turkey', 'Thailand', 'U.K.', 'France', 'Italy', 'Tanzania', 'South Africa', 'Myanmar', 'South Korea', 'Colombia', 'Kenya', 'Spain', 'Ukraine', 'Argentina', 'Sudan', 'Uganda', 'Algeria', 'Iraq', 'Poland', 'Canada', 'Morocco', 'Afghanistan', 'Saudi Arabia', 'Peru', 'Venezuela', 'Malaysia', 'Uzbekistan', 'Mozambique', 'Nepal', 'Ghana', 'Yemen', 'Angola', 'Madagascar', 'North Korea', 'Australia', 'Cameroon', 'C', 'Niger', 'Sri Lanka', 'Romania', 'Burkina Faso', 'Syria', 'Mali', 'Chile', 'Malawi', 'Kazakhstan', 'Zambia', 'Netherlands', 'Guatemala', 'Ecuador', 'Zimbabwe', 'Cambodia', 'Senegal', 'Chad', 'Guinea', 'South Sudan', 'Rwanda', 'Burundi', 'Tunisia', 'Benin', 'Belgium', 'Somalia', 'Cuba', 'Bolivia', 'Haiti', 'Greece', 'Dominican Republic', 'Czech Republic', 'Portugal', 'Azerbaijan', 'Sweden', 'Hungary', 'Belarus', 'United Arab Emirates', 'Tajikistan', 'Serbia', 'Austria', 'Switzerland', 'Israel', 'Honduras', 'Papua New Guinea', 'Jordan', 'Togo', 'Bulgaria', 'Laos', 'Paraguay', 'Sierra Leone', 'Libya', 'Nicaragua', 'El Salvador', 'Kyrgyzstan', 'Lebanon', 'Singapore', 'Denmark', 'Finland', 'Turkmenistan', 'Eritrea', 'Slovakia', 'Norway', 'Central African Republic', 'State of Palestine', 'Costa Rica', 'Congo', 'Ireland', 'Oman', 'Liberia', 'New Zealand', 'Mauritania', 'Croatia', 'Kuwait', 'Moldova', 'Panama', 'Georgia', 'Bosnia and Herzegovina', 'Uruguay', 'Mongolia', 'Armenia', 'Albania', 'Lithuania', 'Jamaica', 'Namibia', 'Botswana', 'Qatar', 'Lesotho', 'Gambia', 'TFYR Macedonia', 'Slovenia', 'Latvia', 'Guinea-Bissau', 'Gabon', 'Bahrain', 'Trinidad and Tobago', 'Swaziland', 'Estonia', 'Mauritius', 'Timor-Leste', 'Cyprus', 'Djibouti', 'Fiji', 'Equatorial Guinea', 'Comoros', 'Bhutan', 'Guyana', 'Montenegro', 'Solomon Islands', 'Luxembourg', 'Suriname', 'Cabo Verde', 'Brunei', 'Malta', 'Bahamas', 'Maldives', 'Belize', 'Iceland', 'Barbados', 'Vanuatu', 'Sao Tome and Principe', 'Samoa', 'Saint Lucia', 'Kiribati', 'St. Vincent', 'Grenada', 'Tonga', 'Micronesia', 'Seychelles', 'Antigua and Barbuda', 'Dominica', 'Andorra', 'Saint Kitts and Nevis', 'Marshall Islands', 'Liechtenstein', 'Monaco', 'San Marino', 'Palau', 'Nauru', 'Tuvalu', 'Holy See']
