# -*- coding:utf-8 -*-

questions = [
    # Asia
    {"name": "China", "state": "Asia", "demonym": "Chinese", "language": "Chinese", "currency": "Renminbi", "capital": "Beijing"},
    {"name": "India", "state": "Asia", "demonym": "Indian", "language": "Hindi", "currency": "rupee", "capital": "New Delhi"},
    {"name": "Indonesia", "state": "Asia", "demonym": "Indonesian", "language": "Indonesian", "currency": "rupiah", "capital": "Jakarta"},
    {"name": "Pakistan", "state": "Asia", "demonym": "Pakistani", "language": "Urdu", "currency": "rupee", "capital": "Islamabad"},
    {"name": "Bangladesh", "state": "Asia", "demonym": "Bangladeshi", "language": "Bengali", "currency": "Taka", "capital": "Dhaka"},
    {"name": "Philippines", "state": "Asia", "demonym": "Philippine", "language": "Filipino", "currency": "Peso", "capital": "Manila"},
    {"name": "Japan", "state": "Asia", "demonym": "Japanese", "language": "Japanese", "currency": "Yen", "capital": "Tokyo"},
    {"name": "Iran", "state": "Asia", "demonym": "Iranian", "language": "Persian", "currency": "Rial", "capital": "Tehran"},
    {"name": "Thailand", "state": "Asia", "demonym": "Thai", "language": "Thai", "currency": "Baht", "capital": "Bangkok"},
    {"name": "Myanmar", "state": "Asia", "demonym": "Myanma", "language": "Burmese", "currency": "Kyat", "capital": "Naypyidaw"},
    {"name": "South Korea", "state": "Asia", "demonym": "Korean", "language": "Korean", "currency": "South Korean won", "capital": "Seoul"},
    {"name": "Iraq", "state": "Asia", "demonym": "Iraqi", "language": "Arabic", "currency": "Iraqi dinar", "capital": "Baghdad"},
    {"name": "Afghanistan", "state": "Asia", "demonym": "Afghan", "language": "Pashto", "currency": "Afghani", "capital": "Kabul"},
    {"name": "Saudi Arabia", "state": "Asia", "demonym": "Saudi", "language": "Arabic", "currency": "Saudi riyal", "capital": "Riyadh"},
    {"name": "United Arab Emirates", "state": "Asia", "demonym": "Emiratis", "language": "Arabic", "currency": "UAE dirham", "capital": "Abu Dhabi"},
    {"name": "Tajikistan", "state": "Asia", "demonym": "Tajik", "language": "Tajik", "currency": "Somoni", "capital": "Dushanbe"},
    {"name": "Laos", "state": "Asia", "demonym": "Laotian", "language": "Lao", "currency": "Kip", "capital": "Vientiane"},
    {"name": "Jordan", "state": "Asia", "demonym": "Jordanian", "language": "Arabic", "currency": "Dinar", "capital": "Amman"},
    {"name": "Qatar", "state": "Asia", "demonym": "Qatari", "language": "Arabic", "currency": "Riyal", "capital": "Doha"},
    {"name": "Bahrain", "state": "Asia", "demonym": "Bahraini", "language": "Arabic", "currency": "Bahraini dinar", "capital": "Manama"},
    {"name": "Timor-Leste", "state": "Asia", "demonym": "East Timorese", "language": "Tetum", "currency": "United States Dollar", "capital": "Dili"},
    {"name": "Bhutan", "state": "Asia", "demonym": "Bhutanese", "language": "Dzongkha", "currency": "Ngultrum", "capital": "Thimphu"},
    {"name": "Brunei", "state": "Asia", "demonym": "Bruneian", "language": "Malay", "currency": "Brunei dollar", "capital": "Bandar Seri Begawan"},
    {"name": "Maldives", "state": "Asia", "demonym": "Maldivian", "language": "Maldivian", "currency": "Maldivian rufiyaa", "capital": "Malé"},
    {"name": "Belize", "state": "Asia", "demonym": "Belizean", "language": "English", "currency": "Belize dollar", "capital": "Belmopan"},
    {"name": "Kyrgyzstan", "state": "Asia", "demonym": "Kyrgyz", "language": "Kyrgyz", "currency": "Som", "capital": "Bishkek"},
    {"name": "Lebanon", "state": "Asia", "demonym": "Lebanese", "language": "Arabic", "currency": "Lebanese pound", "capital": "Beirut"},
    {"name": "Singapore", "state": "Asia", "demonym": "Singaporean", "language": "English", "currency": "Singapore dollar", "capital": "Singapore"},
    {"name": "Oman", "state": "Asia", "demonym": "Omani", "language": "Arabic", "currency": "Rial", "capital": "Muscat"},
    {"name": "Kuwait", "state": "Asia", "demonym": "Kuwaiti", "language": "Arabic", "currency": "Kuwaiti dinar", "capital": "Kuwait City"},
    {"name": "State of Palestine", "state": "Asia", "demonym": "Palestinian", "language": "Arabic", "currency": "Egyptian pound", "capital": "Jerusalem"},
    {"name": "Turkmenistan", "state": "Asia", "demonym": "Turkmen", "language": "Turkmen", "currency": "Turkmen new manat", "capital": "Ashgabat"},
    {"name": "Malaysia", "state": "Asia", "demonym": "Malaysian", "language": "Bahasa Malaysia", "currency": "Ringgit", "capital": "Kuala Lumpur"},
    {"name": "Uzbekistan", "state": "Asia", "demonym": "Uzbek", "language": "Uzbek", "currency": "Uzbekistan som", "capital": "Tashkent"},
    {"name": "Sri Lanka", "state": "Asia", "demonym": "Sri Lankan", "language": "Sinhalese", "currency": "Sri Lankan rupee", "capital": "Sri Jayawardenepura Kotte"},
    {"name": "Nepal", "state": "Asia", "demonym": "Nepali", "language": "Nepali", "currency": "Nepalese rupee", "capital": "Kathmandu"},
    {"name": "North Korea", "state": "Asia", "demonym": "North Korean", "language": "Korean", "currency": "North Korean won", "capital": "Pyongyang"},
    {"name": "Syria", "state": "Asia", "demonym": "Syrian", "language": "Arabic", "currency": "Syrian pound", "capital": "Damascus"},
    {"name": "Yemen", "state": "Asia", "demonym": "Yemeni, Yemenite", "language": "Arabic", "currency": "Yemeni rial", "capital": "Sana'a"},
    {"name": "Cambodia", "state": "Asia", "demonym": "Cambodian, Kampuchean", "language": "Khmer", "currency": "Riel", "capital": "Phnom Penh"},
    # Europe
    {"name": "Russia", "state": "Europe", "demonym": "Russian", "language": "Russian", "currency": "ruble", "capital": "Moscow"},
    {"name": "Germany", "state": "Europe", "demonym": "German", "language": "German", "currency": "Euro", "capital": "Berlin"},
    {"name": "Turkey", "state": "Europe", "demonym": "Turkish", "language": "Turkish", "currency": "lira", "capital": "Ankara"},
    {"name": "U.K.", "state": "Europe", "demonym": "British", "language": "English", "currency": "Pound", "capital": "London"},
    {"name": "France", "state": "Europe", "demonym": "French", "language": "French", "currency": "Euro", "capital": "Paris"},
    {"name": "Italy", "state": "Europe", "demonym": "Italian", "language": "Italian", "currency": "Euro", "capital": "Rome"},
    {"name": "Spain", "state": "Europe", "demonym": "Spanish", "language": "Spanish", "currency": "Euro", "capital": "Madrid"},
    {"name": "Ukraine", "state": "Europe", "demonym": "Ukrainian", "language": "Ukrainian", "currency": "Ukrainian hryvnia", "capital": "Kiev"},
    {"name": "Denmark", "state": "Europe", "demonym": "Danish", "language": "Danish", "currency": "Danish krone", "capital": "Copenhagen"},
    {"name": "Finland", "state": "Europe", "demonym": "Finnish", "language": "Finnish", "currency": "Euro", "capital": "Helsinki"},
    {"name": "Bulgaria", "state": "Europe", "demonym": "Bulgarian", "language": "Bulgarian", "currency": "Lev", "capital": "Sofia"},
    {"name": "Ireland", "state": "Europe", "demonym": "Irish", "language": "Irish", "currency": "Euro", "capital": "Dublin"},
    {"name": "Slovakia", "state": "Europe", "demonym": "Slovak", "language": "Slovak", "currency": "Euro", "capital": "Bratislava"},
    {"name": "Norway", "state": "Europe", "demonym": "Norwegian", "language": "Norwegian", "currency": "Norwegian krone", "capital": "Oslo"},
    {"name": "Armenia", "state": "Europe", "demonym": "Armenian", "language": "Armenian", "currency": "Dram", "capital": "Yerevan"},
    {"name": "Albania", "state": "Europe", "demonym": "Albanian", "language": "Albanian", "currency": "Lek", "capital": "Tirana"},
    {"name": "Lithuania", "state": "Europe", "demonym": "Lithuanian", "language": "Lithuanian", "currency": "Euro", "capital": "Vilnius"},
    {"name": "TFYR Macedonia", "state": "Europe", "demonym": "Macedonian", "language": "Macedonian", "currency": "Macedonian denar", "capital": "Skopje"},
    {"name": "Slovenia", "state": "Europe", "demonym": "Slovene", "language": "Slovene", "currency": "Euro", "capital": "Ljubljana"},
    {"name": "Latvia", "state": "Europe", "demonym": "Latvian", "language": "Latvian", "currency": "Euro", "capital": "Riga"},
    {"name": "New Zealand", "state": "Europe", "demonym": "New Zealander", "language": "English", "currency": "New Zealand dollar", "capital": "Wellington"},
    {"name": "Bosnia and Herzegovina", "state": "Europe", "demonym": "Bosnian", "language": "Bosnian", "currency": "Convertible mark", "capital": "Sarajevo"},
    {"name": "Croatia", "state": "Europe", "demonym": "Croatian", "language": "Croatian", "currency": "Kuna", "capital": "Zagreb"},
    {"name": "Estonia", "state": "Europe", "demonym": "Estonian", "language": "Estonian", "currency": "Euro", "capital": "Tallinn"},
    {"name": "Cyprus", "state": "Europe", "demonym": "Cypriot", "language": "Armenian", "currency": "Euro", "capital": "Nicosia"},
    {"name": "Montenegro", "state": "Europe", "demonym": "Montenegrin", "language": "Montenegrin", "currency": "Euro", "capital": "Podgorica"},
    {"name": "Andorra", "state": "Europe", "demonym": "Andorran", "language": "Catalan", "currency": "Euro", "capital": "Andorra la Vella"},
    {"name": "Liechtenstein", "state": "Europe", "demonym": "Andorran", "language": "German", "currency": "Swiss franc", "capital": "Vaduz"},
    {"name": "Monaco", "state": "Europe", "demonym": "Monacan", "language": "French", "currency": "Euro", "capital": "Monaco-ville"},
    {"name": "San Marino", "state": "Europe", "demonym": "Sammarinese", "language": "Italian", "currency": "Euro", "capital": "City of San Marino"},
    {"name": "Holy See", "state": "Europe", "demonym": "Vatican", "language": "Italian", "currency": "Euro", "capital": "Vatican City"},
    {"name": "Tonga", "state": "Europe", "demonym": "Tongan", "language": "Tongan", "currency": "Pa", "capital": "Nuku"},
    # {"name": "St. Vincent", "state": "Europe", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Malta", "state": "Europe", "demonym": "Maltese", "language": "Maltese", "currency": "Euro", "capital": "Valletta"},
    {"name": "Luxembourg", "state": "Europe", "demonym": "Luxembourgish,", "language": "French", "currency": "Euro", "capital": "Luxembourg City"},
    {"name": "Moldova", "state": "Europe", "demonym": "Moldovan", "language": "Romanian", "currency": "Leu", "capital": "Chișinău"},
    {"name": "Czech Republic", "state": "Europe", "demonym": "Czech", "language": "Czech", "currency": "Czech koruna", "capital": "Prague"},
    {"name": "Portugal", "state": "Europe", "demonym": "Portuguese", "language": "Portuguese", "currency": "Euro", "capital": "Lisbon"},
    {"name": "Azerbaijan", "state": "Europe", "demonym": "Azerbaijani", "language": "Azerbaijani", "currency": "Manat", "capital": "Baku"},
    {"name": "Sweden", "state": "Europe", "demonym": "Swede", "language": "Swedish", "currency": "Swedish krona", "capital": "Stockholm"},
    {"name": "Hungary", "state": "Europe", "demonym": "Hungarian", "language": "Hungarian", "currency": "Forint", "capital": "Budapest"},
    {"name": "Belarus", "state": "Europe", "demonym": "Belarusian", "language": "Belarusian", "currency": "Belarusian ruble", "capital": "Minsk"},
    {"name": "Greece", "state": "Europe", "demonym": "Greek", "language": "Greek", "currency": "Euro", "capital": "Athens"},
    {"name": "Kazakhstan", "state": "Europe", "demonym": "Kazakh", "language": "Kazakh", "currency": "Tenge", "capital": "Astana"},
    {"name": "Romania", "state": "Europe", "demonym": "Romanian", "language": "Romanian", "currency": "Romanian leu", "capital": "Bucharest"},
    {"name": "Belgium", "state": "Europe", "demonym": "Belgian", "language": "Dutch", "currency": "Euro", "capital": "Brussels"},
    {"name": "Serbia", "state": "Europe", "demonym": "Serbian", "language": "Serbian", "currency": "Serbian dinar", "capital": "Belgrade"},
    {"name": "Austria", "state": "Europe", "demonym": "Austrian", "language": "Austrian German", "currency": "Euro", "capital": "Vienna"},
    {"name": "Switzerland", "state": "Europe", "demonym": "English:", "language": "German", "currency": "Swiss franc", "capital": "Bern"},
    {"name": "Iceland", "state": "Europe", "demonym": "Icelander", "language": "Icelandic", "currency": u"Icelandic króna", "capital": u"Reykjavík"},
    # North America
    {"name": "U.S.", "state": "North America", "demonym": "American", "language": "English", "currency": "dollar", "capital": "Washington, D.C."},
    {"name": "Mexico", "state": "North America", "demonym": "Mexican", "language": "Spanish", "currency": "Peso", "capital": "Mexico City"},
    {"name": "Canada", "state": "North America", "demonym": "Canadian", "language": "English", "currency": "Canadian dollar", "capital": "Ottawa"},
    {"name": "Bahamas", "state": "North America", "demonym": "Bahamian", "language": "English", "currency": "Bahamian dollar", "capital": "Nassau"},
    {"name": "Barbados", "state": "North America", "demonym": "Barbadian", "language": "English", "currency": "Bajan dollar", "capital": "Bridgetown"},
    {"name": "Haiti", "state": "North America", "demonym": "Haitian", "language": "French", "currency": "Haitian gourde", "capital": "Port-au-Prince"},
    {"name": "Guatemala", "state": "North America", "demonym": "Guatemalan", "language": "Spanish", "currency": "Quetzal", "capital": "Guatemala City"},
    {"name": "Dominican Republic", "state": "North America", "demonym": "Dominican", "language": "Spanish", "currency": "Peso", "capital": "Santo Domingo"},
    {"name": "Cuba", "state": "North America", "demonym": "Cuban", "language": "Spanish", "currency": "Peso", "capital": "Havana"},
    {"name": "Honduras", "state": "North America", "demonym": "Honduran", "language": "Spanish", "currency": "Lempira", "capital": "Tegucigalpa"},
    {"name": "El Salvador", "state": "North America", "demonym": "Salvadoran", "language": "Spanish", "currency": "United States dollar", "capital": "San Salvador"},
    {"name": "Antigua and Barbuda", "state": "North America", "demonym": "Antiguan", "language": "English", "currency": "East Caribbean dollar", "capital": "St. John's"},
    {"name": "Dominica", "state": "North America", "demonym": "Dominican", "language": "English", "currency": "East Caribbean dollar", "capital": "Roseau"},
    {"name": "Saint Kitts and Nevis", "state": "North America", "demonym": "Kittitian or Nevisian", "language": "English", "currency": "East Caribbean dollar", "capital": "Basseterre"},
    {"name": "Grenada", "state": "North America", "demonym": "Grenadian", "language": "English", "currency": "East Caribbean dollar", "capital": "St. George's"},
    {"name": "Saint Lucia", "state": "North America", "demonym": "Saint Lucian", "language": "English", "currency": "East Caribbean dollar", "capital": "Castries"},
    # South America
    {"name": "Colombia", "state": "South America", "demonym": "Colombian", "language": "Spanish", "currency": "Peso", "capital": "Bogotá"},
    {"name": "Argentina", "state": "South America", "demonym": "Argentine", "language": "Spanish", "currency": "Peso", "capital": "Buenos Aires"},
    {"name": "Trinidad and Tobago", "state": "South America", "demonym": "Trinidadian", "language": "English", "currency": "Trinidad and Tobago dollar", "capital": "Port of Spain"},
    {"name": "Guyana", "state": "South America", "demonym": "Guyanese", "language": "English", "currency": "Guyanese dollar", "capital": "Georgetown"},
    {"name": "Suriname", "state": "South America", "demonym": "Surinamese", "language": "Dutch", "currency": "Surinamese dollar", "capital": "Georgetown"},
    {"name": "Chile", "state": "South America", "demonym": "Chilean", "language": "Spanish", "currency": "Peso", "capital": "Santiago"},
    {"name": "Peru", "state": "South America", "demonym": "Peruvian", "language": "Spanish", "currency": "Sol", "capital": "Lima"},
    {"name": "Ecuador", "state": "South America", "demonym": "Ecuadorian", "language": "Spanish", "currency": "United States dollar", "capital": "Quito"},
    {"name": "Bolivia", "state": "South America", "demonym": "Bolivian", "language": "Quechua", "currency": "Boliviano", "capital": "Sucre"},
    {"name": "Panama", "state": "South America", "demonym": "Panamanian", "language": "Spanish", "currency": "Balboa", "capital": "Panama City"},
    {"name": "Uruguay", "state": "South America", "demonym": "Uruguayan", "language": "Spanish", "currency": "Uruguayan peso", "capital": "Montevideo"},
    # Oceania
    {"name": "Solomon Islands", "state": "Oceania", "demonym": "Solomon Islander", "language": "English", "currency": "Solomon Islands dollar", "capital": "Honiara"},
    {"name": "Fiji", "state": "Oceania", "demonym": "Fijian", "language": "English", "currency": "Fijian dollar", "capital": "Suva"},
    {"name": "Papua New Guinea", "state": "Oceania", "demonym": "Papua New Guinean", "language": "English", "currency": "Papua New Guinean kina", "capital": "Port Moresby"},
    {"name": "Australia", "state": "Oceania", "demonym": "Australian", "language": "English", "currency": "Australian dollar", "capital": "Canberra"},
    {"name": "Vanuatu", "state": "Oceania", "demonym": "Ni-Vanuatu", "language": "Bislama", "currency": "Vanuatu vatu", "capital": "Port Vila"},
    {"name": "Samoa", "state": "Oceania", "demonym": "Samoan", "language": "Samoan", "currency": "Tala", "capital": "Apia"},
    {"name": "Kiribati", "state": "Oceania", "demonym": "I-Kiribati", "language": "English", "currency": "Kiribati dollar", "capital": "Tarawa"},
    {"name": "Micronesia", "state": "Oceania", "demonym": "Micronesian", "language": "Micronesian", "currency": "dollar", "capital": "Palikir"},
    {"name": "Marshall Islands", "state": "Oceania", "demonym": "Marshallese", "language": "Marshallese", "currency": "United States dollar", "capital": "US Associated State"},
    {"name": "Palau", "state": "Oceania", "demonym": "Palauan", "language": "English", "currency": "United States dollar", "capital": "Ngerulmud"},
    {"name": "Nauru", "state": "Oceania", "demonym": "Nauruan", "language": "Nauruan", "currency": "Australian dollar", "capital": "Yaren"},
    {"name": "Tuvalu", "state": "Oceania", "demonym": "Tuvaluan", "language": "Tuvaluan", "currency": "Tuvaluan dollar", "capital": "Funafuti"},
    # Africa
    {"name": "Nigeria", "state": "Africa", "demonym": "Nigerian", "language": "English", "currency": "Naira", "capital": "Abuja"},
    {"name": "Ethiopia", "state": "Africa", "demonym": "Ethiopian", "language": "Ethiopian", "currency": "Birr", "capital": "Addis Ababa"},
    {"name": "Egypt", "state": "Africa", "demonym": "Egyptian", "language": "Arabic", "currency": "Egyptian pound", "capital": "Cairo"},
    {"name": "DR Congo", "state": "Africa", "demonym": "Congolese", "language": "French", "currency": "franc", "capital": "Kinshasa"},
    {"name": "Tanzania", "state": "Africa", "demonym": "Tanzanian", "language": "	Swahili", "currency": "Tanzanian shilling", "capital": "Dodoma"},
    {"name": "South Africa", "state": "Africa", "demonym": "South African", "language": "IsiZulu", "currency": "rand", "capital": "Pretoria"},
    {"name": "Kenya", "state": "Africa", "demonym": "Kenyan", "language": "Kiswahili", "currency": "Kenyan shilling", "capital": "Nairobi"},
    {"name": "Sudan", "state": "Africa", "demonym": "Sudanese", "language": "Arabic", "currency": "Sudanese pound", "capital": "Khartoum"},
    {"name": "Uganda", "state": "Africa", "demonym": "Ugandan", "language": "English", "currency": "Ugandan shilling", "capital": "Kampala"},
    {"name": "Algeria", "state": "Africa", "demonym": "Algerian", "language": "Arabic", "currency": "Dinar", "capital": "Algiers"},
    {"name": "Morocco", "state": "Africa", "demonym": "Moroccan", "language": "Arabic", "currency": "Moroccan dirham", "capital": "Rabat"},
    {"name": "Angola", "state": "Africa", "demonym": "Angolan", "language": "Portuguese", "currency": "Kwanza", "capital": "Luanda"},
    {"name": "Madagascar", "state": "Africa", "demonym": "Malagasy", "language": "Malagasy", "currency": "Malagasy ariary", "capital": "Antananarivo"},
    {"name": "Ghana", "state": "Africa", "demonym": "Ghanaian", "language": "English", "currency": "Ghana cedi", "capital": "Accra"},
    {"name": "Mozambique", "state": "Africa", "demonym": "Mozambican", "language": "Portuguese", "currency": "Mozambican metical", "capital": "Maputo"},
    {"name": "Niger", "state": "Africa", "demonym": "Nigerien", "language": "French", "currency": "West African CFA franc", "capital": "Niamey"},
    {"name": "Burkina Faso", "state": "Africa", "demonym": "Burkinabe", "language": "French", "currency": "West African CFA franc", "capital": "Ouagadougou"},
    {"name": "Mali", "state": "Africa", "demonym": "Malian", "language": "French", "currency": "West African CFA franc", "capital": "Bamako"},
    {"name": "Malawi", "state": "Africa", "demonym": "Malawian", "language": "English", "currency": "Kwacha", "capital": "Lilongwe"},
    {"name": "Zambia", "state": "Africa", "demonym": "Zambian", "language": "English", "currency": "Zambian kwacha", "capital": "Lusaka"},
    {"name": "Zimbabwe", "state": "Africa", "demonym": "Zimbabwean", "language": "English", "currency": "United States dollar", "capital": "Harare"},
    {"name": "Senegal", "state": "Africa", "demonym": "Senegalese", "language": "French", "currency": "CFA franc", "capital": "Dakar"},
    {"name": "Chad", "state": "Africa", "demonym": "Chadian", "language": "Arabic", "currency": "Central African CFA franc", "capital": "N'Djamena"},
    {"name": "Guinea", "state": "Africa", "demonym": "Guinean", "language": "French", "currency": "Guinean franc", "capital": "Conakry"},
    {"name": "South Sudan", "state": "Africa", "demonym": "South Sudanese", "language": "English", "currency": "South Sudanese pound", "capital": "Juba"},
    {"name": "Rwanda", "state": "Africa", "Rwandan": "Kinyarwanda", "language": "Kinyarwanda", "currency": "Rwandan franc", "capital": "Kigali"},
    {"name": "Burundi", "state": "Africa", "demonym": "Burundian", "language": "French", "currency": "Burundian franc", "capital": "Bujumbura"},
    {"name": "Tunisia", "state": "Africa", "demonym": "Tunisian", "language": "Arabic", "currency": "Tunisian dinar", "capital": "Tunis"},
    {"name": "Benin", "state": "Africa", "demonym": "Beninese", "language": "French", "currency": "West African CFA franc", "capital": "Porto-Novo"},
    {"name": "Somalia", "state": "Africa", "demonym": "Somali", "language": "Somali", "currency": "Somali shilling", "capital": "Mogadishu"},
    {"name": "Togo", "state": "Africa", "demonym": "Togolese", "language": "French", "currency": "CFA franc", "capital": u"Lomé"},
    {"name": "Israel", "state": "Africa", "demonym": "Israeli", "language": "Hebrew", "currency": "New shekel", "capital": "Jerusalem"},
    {"name": "Eritrea", "state": "Africa", "demonym": "Eritrean", "language": "Tigrinya", "currency": "Nakfa", "capital": "Asmara"},
    {"name": "Sierra Leone", "state": "Africa", "demonym": "Sierra Leonean", "language": "English", "currency": "Leone", "capital": "Freetown"},
    {"name": "Libya", "state": "Africa", "demonym": "Libyan", "language": "Arabic", "currency": "Libyan dinar", "capital": "Tripoli"},
    {"name": "Central African Republic", "state": "Africa", "demonym": "Central African", "language": "French", "currency": "Central African CFA franc", "capital": "Bangui"},
    {"name": "Mauritania", "state": "Africa", "demonym": "Mauritanian", "language": "Arabic", "currency": "Ouguiya", "capital": "Nouakchott"},
    {"name": "Liberia", "state": "Africa", "demonym": "Liberian", "language": "English", "currency": "Liberian dollar", "capital": "Monrovia"},
    # {"name": "Georgia", "state": "", "demonym": "", "language": "", "currency": "", "capital": ""},
    {"name": "Jamaica", "state": "Africa", "demonym": "Jamaican", "language": "English", "currency": "Jamaican dollar", "capital": "Kingston"},
    {"name": "Namibia", "state": "Africa", "demonym": "Namibian", "language": "English", "currency": "Namibian dollar", "capital": "Windhoek"},
    {"name": "Botswana", "state": "Africa", "demonym": "Batswana", "language": "Setswana", "currency": "Pula", "capital": "Gaborone"},
    {"name": "Lesotho", "state": "Africa", "demonym": "Mosotho", "language": "Sotho", "currency": "Lesotho loti", "capital": "Maseru"},
    {"name": "Gambia", "state": "Africa", "demonym": "Gambian", "language": "English", "currency": "Dalasi", "capital": "Banjul"},
    {"name": "Guinea-Bissau", "state": "Africa", "demonym": "Bissau-Guinean", "language": "Portuguese", "currency": "West African CFA franc", "capital": "Bissau"},
    {"name": "Gabon", "state": "Africa", "demonym": "Gabonese", "language": "French", "currency": "Central African CFA franc", "capital": "Libreville"},
    {"name": "Swaziland", "state": "Africa", "demonym": "Swazi", "language": "	Swazi", "currency": "South African rand", "capital": "Lobamba"},
    {"name": "Mauritius", "state": "Africa", "demonym": "Mauritian", "language": "Mauritian Creole", "currency": "Mauritian rupee", "capital": "Port Louis"},
    {"name": "Djibouti", "state": "Africa", "demonym": "Djiboutian", "language": "French", "currency": "Djiboutian franc", "capital": "Djibouti City"},
    {"name": "Equatorial Guinea", "state": "Africa", "demonym": "Equatoguinean", "language": "Spanish", "currency": "Central African CFA franc", "capital": "Malabo"},
    {"name": "Comoros", "state": "Africa", "demonym": "Comorian", "language": "Comorian", "currency": "Comorian franc", "capital": "Moroni"},
    {"name": "Cabo Verde", "state": "Africa", "demonym": "Cape Verdean", "language": "Portuguese", "currency": "Cape Verdean escudo", "capital": "Praia"},
    {"name": "Sao Tome and Principe", "state": "Africa", "demonym": "Santomean", "language": "Portuguese", "currency": "Dobra", "capital": u"São Tomé"},
    {"name": "Seychelles", "state": "Africa", "demonym": "Seychellois", "language": "English", "currency": "Seychellois rupee", "capital": "Victoria"},
]

countries_list = ['China', 'India', 'U.S.', 'Indonesia', 'Brazil', 'Pakistan', 'Nigeria', 'Bangladesh', 'Russia', 'Mexico', 'Japan', 'Ethiopia', 'Philippines', 'Viet Nam', 'Egypt', 'DR Congo', 'Iran', 'Germany', 'Turkey', 'Thailand', 'U.K.', 'France', 'Italy', 'Tanzania', 'South Africa', 'Myanmar', 'South Korea', 'Colombia', 'Kenya', 'Spain', 'Ukraine', 'Argentina', 'Sudan', 'Uganda', 'Algeria', 'Iraq', 'Poland', 'Canada', 'Morocco', 'Afghanistan', 'Saudi Arabia', 'Peru', 'Venezuela', 'Malaysia', 'Uzbekistan', 'Mozambique', 'Nepal', 'Ghana', 'Yemen', 'Angola', 'Madagascar', 'North Korea', 'Australia', 'Cameroon', 'C', 'Niger', 'Sri Lanka', 'Romania', 'Burkina Faso', 'Syria', 'Mali', 'Chile', 'Malawi', 'Kazakhstan', 'Zambia', 'Netherlands', 'Guatemala', 'Ecuador', 'Zimbabwe', 'Cambodia', 'Senegal', 'Chad', 'Guinea', 'South Sudan', 'Rwanda', 'Burundi', 'Tunisia', 'Benin', 'Belgium', 'Somalia', 'Cuba', 'Bolivia', 'Haiti', 'Greece', 'Dominican Republic', 'Czech Republic', 'Portugal', 'Azerbaijan', 'Sweden', 'Hungary', 'Belarus', 'United Arab Emirates', 'Tajikistan', 'Serbia', 'Austria', 'Switzerland', 'Israel', 'Honduras', 'Papua New Guinea', 'Jordan', 'Togo', 'Bulgaria', 'Laos', 'Paraguay', 'Sierra Leone', 'Libya', 'Nicaragua', 'El Salvador', 'Kyrgyzstan', 'Lebanon', 'Singapore', 'Denmark', 'Finland', 'Turkmenistan', 'Eritrea', 'Slovakia', 'Norway', 'Central African Republic', 'State of Palestine', 'Costa Rica', 'Congo', 'Ireland', 'Oman', 'Liberia', 'New Zealand', 'Mauritania', 'Croatia', 'Kuwait', 'Moldova', 'Panama', 'Georgia', 'Bosnia and Herzegovina', 'Uruguay', 'Mongolia', 'Armenia', 'Albania', 'Lithuania', 'Jamaica', 'Namibia', 'Botswana', 'Qatar', 'Lesotho', 'Gambia', 'TFYR Macedonia', 'Slovenia', 'Latvia', 'Guinea-Bissau', 'Gabon', 'Bahrain', 'Trinidad and Tobago', 'Swaziland', 'Estonia', 'Mauritius', 'Timor-Leste', 'Cyprus', 'Djibouti', 'Fiji', 'Equatorial Guinea', 'Comoros', 'Bhutan', 'Guyana', 'Montenegro', 'Solomon Islands', 'Luxembourg', 'Suriname', 'Cabo Verde', 'Brunei', 'Malta', 'Bahamas', 'Maldives', 'Belize', 'Iceland', 'Barbados', 'Vanuatu', 'Sao Tome and Principe', 'Samoa', 'Saint Lucia', 'Kiribati', 'St. Vincent', 'Grenada', 'Tonga', 'Micronesia', 'Seychelles', 'Antigua and Barbuda', 'Dominica', 'Andorra', 'Saint Kitts and Nevis', 'Marshall Islands', 'Liechtenstein', 'Monaco', 'San Marino', 'Palau', 'Nauru', 'Tuvalu', 'Holy See']
